### ISSUE TITLE
Permission Denied in Android Version 11

### ISSUE THREAD

**Issue by Asalerm** [kengoon/PyJniusTester#2]
Good day sir.

I have downloaded your app pyjniustester but each time i tried to write a file to external or internal storage it shows permission not granted but only in Android version 11 but after i have a research all i find out is that Manage_External_Storage permission is not granted at all please am i wrong or was it that you didn't update the app???

**Comment by kengoon** [comment]
the pyjnius tester app is built to be flexible. the intention is for you to
run and test pyjnius or java code. all the permission needed were bundled
into the app. you have to request read and write permission your self by
writing the code to request read and write storage permission  in the app
editor itself.

**Comment by kengoon** [comment]
The https://github.com/Android-for-Python/androidstorage4kivy has been added, to the requirement. you can check out the repo to see how to use it
